### ISSUE TITLE
Seems incorrect with deterministic search

### ISSUE THREAD

**Issue by larkz** [JunTaoLuo/KotlinMCTS#2]
Made a quick run and visualization with your code, and it looks like its producing some unexpected results with transition probability set to 1.

I'm getting the results like this, some of the actions, despite transition probability set to 1, still gives questionable solves.

```
[→, ↑, ↑, ↑]
[→, R, ←, X]
[→, ↓, ←, ↓]
[↓, X, ↓, ↓]
```
Let me know if you are getting the same or if I'm running something incorrectly, code changes in https://github.com/JunTaoLuo/KotlinMCTS/pull/1 provide the visualization functionality.

**Comment by JunTaoLuo** [comment]
As discussed during our meeting, there were issues in the visualization functions which has been fixed as of https://github.com/JunTaoLuo/KotlinMCTS/commit/17b8bbaf46724ab5d2fe46f2cb1fa203107053b4. There still remains some unexplained results which seem to be an artifact of how MCTS works.
